version: "3"
services:
  grafana:
    image: grafana/grafana:7.5.2
    container_name: grafana
    restart: unless-stopped
    user: "472"
    ports:
      - 3500:3000
    volumes:
      - ./datasources:/etc/grafana/provisioning/datasources
      - ./grafana-data:/var/lib/grafana
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:1.8.3
    container_name: influxdb
    volumes:
      - ./influxdb-data:/var/lib/influxdb
    ports:
      - 8083:8083
      - 8086:8086
    environment:
      - INFLUXDB_ADMIN_USER="admin"
      - INFLUXDB_ADMIN_PASSWORD="password"
      - INFLUXDB_DB="speedtest"

  speedtest:
    build: .
    container_name: speedtest
    volumes:
      - './speedtest.py:/speedtest.py'
    environment:
      - LOOP=true
      - LOOP_DELAY=1800
      - DB_SAVE=true
      - DB_HOST=influxdb
      - DB_NAME=speedtest
      - DB_USERNAME=admin
      - DB_PASSWORD=password
    depends_on:
      - influxdb
    restart: "always"
    deploy:
      restart_policy:
        delay: 60s